import = ["/home/alpha/.config/alacritty/themes/catppuccin/catppuccin-macchiato.toml"]
live_config_reload = true

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"
shape = "Block"

# FiraCode
[font]
size = 13.5
[font.bold]
family = "FiraCode Nerd Font"
[font.bold_italic]
family = "FiraCode Nerd Font"
[font.italic]
family = "FiraCode Nerd Font"
[font.normal]
family = "FiraCode Nerd Font"

# # JetBrains
# [font]
# size = 12.0
# [font.bold]
# family = "JetBrains Mono Nerd Font"
# [font.bold_italic]
# family = "JetBrains Mono Nerd Font"
# [font.italic]
# family = "JetBrains Mono Nerd Font"
# [font.normal]
# family = "JetBrains Mono Nerd Font"

# # Hack
# [font]
# size = 12.0
# [font.bold]
# family = "Hack Nerd Font"
# style = "Bold"
# [font.bold_italic]
# family = "Hack Nerd Font"
# style = "Bold Italic"
# [font.italic]
# family = "Hack Nerd Font"
# style = "Italic"
# [font.normal]
# family = "Hack Nerd Font"
# style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.92
startup_mode = "Maximized"

[window.padding]
x = 3
y = 3
